UserData = (
    ("Leader", "Leader"),
    ("Co-Leader", "Co-Leader"),
    ("Project Assistant", "Project Assistant"),
    ("Project Core", "Project Core"),
    ("Treasurer", "Treasurer"),
    ("Team Support", "Team Support"),
    ("Participant", "Participant"),
    ("Substitute", "Substitute"),
    ("Task Manager", "Task Manager"),
    ("Project Manager", "Project Manager"),
    ("Documentator", "Documentator"),
    ("General Researcher", "General Researcher"),
    ("Resource Researcher", "Resource Researcher"),
)
